# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files first to leverage Docker cache
COPY package.json package-lock.json ./

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts

# Copy the remaining source code
COPY . .

# Build the TypeScript source
RUN npm run build

# Expose default port if necessary (currently not specified, but MCP servers may use stdio)

# Specify the default command
CMD [ "node", "build/index.js" ]
